### ISSUE TITLE
Focal length

### ISSUE THREAD

**Issue by fabvio** [bosch-ros-pkg/bstld#10]
Hi, thanks for sharing your dataset. Could you please provide additional details about the acquisition system? In particular, do you know the value of the focal length of the camera?

**Comment by karstenBehrendt** [comment]
Unfortunately, I cannot share that information. All I can tell you is that the camera is somewhat close to the MPC2 https://www.bosch-mobility-solutions.com/media/global/products-and-services/passenger-cars-and-light-commercial-vehicles/driver-assistance-systems/lane-departure-warning/product-page-multi-purpose-camera/product-data-sheet-multi-purpose-camera.pdf
