### ISSUE TITLE
有关数据的标注

### ISSUE THREAD

**Issue by ReaJyf** [bosch-ros-pkg/bstld#13]
请问这个数据集的标注为什么不是整数，我使用的rgb的图像需要针对这一点做什么额外的处理吗？

**Comment by karstenBehrendt** [comment]
I'm sorry but I do not speak chinese. According to google "May I ask why the annotations of this dataset are not integers, do the rgb images I use need to do extra processing for this?"

The annotations are in floating points because they were annotated in zoomed in images. This means that you can click onto specific parts of a pixel. This likely does not make it more accurate in any way but was just easy to implement. Just int(round()) the values for their pixel label.

The RGB images do not need any extra processing.

**Comment by ReaJyf** [comment]
That's what I want to know.


Thanks very much.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Karsten Behrendt"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月28日(星期六) 凌晨3:29
收件人:&nbsp;"bosch-ros-pkg/bstld"<bstld@noreply.github.com&gt;;
抄送:&nbsp;"Rea"<1035897133@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bosch-ros-pkg/bstld] 有关数据的标注 (#13)




I'm sorry but I do not speak chinese. According to google "May I ask why the annotations of this dataset are not integers, do the rgb images I use need to do extra processing for this?"
 
The annotations are in floating points because they were annotated in zoomed in images. This means that you can click onto specific parts of a pixel. This likely does not make it more accurate in any way but was just easy to implement. Just int(round()) the values for their pixel label.
 
The RGB images do not need any extra processing.

**Comment by ReaJyf** [comment]
Hi, I have a question about occluded tracffic light.


Did&nbsp; your test dataset include occluded tracffic light when you calculate mAP.


Because I don't find the referenced code of [from object_detection.utils.object_detection_evaluation import ObjectDetectionEvaluation] in bstld.evaluation.evaluate.py from your project. I think I have to consult you about this question.


Happy new year!


Jiao.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Karsten Behrendt"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月28日(星期六) 凌晨3:29
收件人:&nbsp;"bosch-ros-pkg/bstld"<bstld@noreply.github.com&gt;;
抄送:&nbsp;"Rea"<1035897133@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bosch-ros-pkg/bstld] 有关数据的标注 (#13)




I'm sorry but I do not speak chinese. According to google "May I ask why the annotations of this dataset are not integers, do the rgb images I use need to do extra processing for this?"
 
The annotations are in floating points because they were annotated in zoomed in images. This means that you can click onto specific parts of a pixel. This likely does not make it more accurate in any way but was just easy to implement. Just int(round()) the values for their pixel label.
 
The RGB images do not need any extra processing.

**Comment by karstenBehrendt** [comment]
Hi @ReaJyf https://github.com/bosch-ros-pkg/bstld/blob/master/evaluation/evaluate.py contains the complete evaluation part. Occluded objects are not evaluated separately (if I remember correctly), i.e., they are part of the test set evaluation. Removing them would increase your accuracy

Here's the referenced code: https://github.com/tensorflow/models/blob/master/research/object_detection/utils/object_detection_evaluation.py
