### ISSUE TITLE
Which Tensorflow version

### ISSUE THREAD

**Issue by sharmalakshay93** [bosch-ros-pkg/bstld#16]
Hi,

I was unable to figure out what TF version is recommended for use. Could you please clarify? Alternatively, if you could add this (and any other library versions) to `requirements.txt` please. 

Thanks!

**Comment by karstenBehrendt** [comment]
Hi @sharmalakshay93 , yes, that is definitely something that I messed up.

The last commit was two years ago on Dec 11, 2018, so your best option would be to try tensorflow 1 (with the tensorflow/models repo)  from that time. Unfortunately, I will not be able to fix this at the moment. Please extend the requirements.txt if you get it running.
