### ISSUE TITLE
No Instruction on Inference.py

### ISSUE THREAD

**Issue by Adrg01** [bosch-ros-pkg/bstld#17]
Hello

I am a student trying to recreate a research paper for which I need to use bstld datset trained SSD architecture with Mobilenet_v1. However inference.py lacks instructions on how to use it to get a pre-trained model.

**Comment by karstenBehrendt** [comment]
Hi, there is not pre-trained model unfortunately. The underlying framework likely also changed too much to be used in 2021. I think your best bet would be to to take an existing framework and just train it locally on the data. I would be super happy to add your resulting model to the repo.

Unfortunately, publishing trained models was not an option for me at the time
