### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by AGrosserHH** [bosch-ros-pkg/bstld#2]
You are getting an error with  OSError: [Errno Could not open image path] D:\net\pal-soc1.us.bosch.com\ifs\data\Shared_Exports\deep_learning_data\traffic_lights\university_run1\24068.png

**Comment by proan** [comment]
This seems to be a problem in your yaml file. Make sure you have downloaded the sample dataset and have permissions to access the files.

**Comment by karstenBehrendt** [comment]
Issue is confirmed. The RGB test set yaml file contains complete files which should not be the case. Temporary fix is to replace the base path be rgb/university_run1/. We will update the label file.

**Comment by karstenBehrendt** [comment]
The annotation paths for the test set have been updated.
