### ISSUE TITLE
Cannot Open Dataset Files

### ISSUE THREAD

**Issue by nradwan** [bosch-ros-pkg/bstld#3]
Hello,

I downloaded the RGB dataset files from the link provided in the ReadMe. However they were all downloaded as binaries. Looking at the code I see that the input to any of the scripts is a yaml file which I assume would be inside the dataset folders. How can I open/convert to another format?

Thanks!

**Comment by karstenBehrendt** [comment]
Hi @nradwan - Thank you for the question. Can you please provide a bit more information?

- What are the files that you downloaded? They should be dataset_train_rgb.zip.001, dataset_train_rgb.zip.002 ...
- Which operating system are you using?
The yaml files can be found within the zip files. The probably easiest way to unzip the files is to use 7-zip, see https://hiro.bsd.uchicago.edu/node/3168

**Comment by nradwan** [comment]
Oh that clears it up. I was attempting to open with unzip and it didn't work. Was able to extract everything successfully now. Thank you for your help!

**Comment by Rishabh-halo** [comment]
I can not see any yaml file inside the zip files.

**Comment by karstenBehrendt** [comment]
The labels are stored within the repo. See https://github.com/bosch-ros-pkg/bstld/tree/master/label_files
