### ISSUE TITLE
'IndexError: list index out of range' when running the to_tfrecords.py file

### ISSUE THREAD

**Issue by GenuineYZR** [bosch-ros-pkg/bstld#8]
Hi, all
Following the 'Tensorflow object detection example' RAEDME, I got an error like this when compiling the to_tfrecords.py file

> Traceback (most recent call last):
  File "D:\Udacity\Self-driving_car\projects\Term3\P3\models\research\bstld\tf_object_detection\to_tfrecords.py", line 195, in <module>
    create_datasets(config)
  File "D:\Udacity\Self-driving_car\projects\Term3\P3\models\research\bstld\tf_object_detection\to_tfrecords.py", line 149, in create_datasets
    train_labels, valid_labels = split_train_labels(train_labels)
  File "D:\Udacity\Self-driving_car\projects\Term3\P3\models\research\bstld\tf_object_detection\to_tfrecords.py", line 124, in split_train_labels
    train_videos = list(map(lambda x: x['path'].split('/')[-2], train_labels))
  File "D:\Udacity\Self-driving_car\projects\Term3\P3\models\research\bstld\tf_object_detection\to_tfrecords.py", line 124, in <lambda>
    train_videos = list(map(lambda x: x['path'].split('/')[-2], train_labels))
IndexError: list index out of range

I am using the updated label files in the label_files folder. Is there any way to solve this? Many thanks~

**Comment by karstenBehrendt** [comment]
I will look into it today and will get back to you if I need some further information

**Comment by karstenBehrendt** [comment]
Could not confirm. I added a few checks, can you pull and check if you get an error? If not, can you provide the content of train_labels and specifically train_labels[0]?
There is a chance that instead of having the yaml files, you downloaded the github links as train/test.yaml

**Comment by GenuineYZR** [comment]
Hi @karstenBehrendt Thanks for taking a look~
I pulled the updated repository and compiled the to_tfrecords.py again and I got an error below:

> Traceback (most recent call last):
  File "D:\Udacity\Self-driving_car\projects\Term3\P3\models\research\bstld\tf_object_detection\to_tfrecords.py", line 193, in <module>
    create_datasets(config)
  File "D:\Udacity\Self-driving_car\projects\Term3\P3\models\research\bstld\tf_object_detection\to_tfrecords.py", line 152, in create_datasets
    train_labels, valid_labels = split_train_labels(train_labels)
  File "D:\Udacity\Self-driving_car\projects\Term3\P3\models\research\bstld\tf_object_detection\to_tfrecords.py", line 127, in split_train_labels
    train_videos = [train_label['path'].split('/')[-2] for train_label in train_labels]
  File "D:\Udacity\Self-driving_car\projects\Term3\P3\models\research\bstld\tf_object_detection\to_tfrecords.py", line 127, in <listcomp>
    train_videos = [train_label['path'].split('/')[-2] for train_label in train_labels]
IndexError: list index out of range

Also I can open the train.yaml with the VScode editor and the train_yaml[0] is like below:

> - boxes: []
  path: ./rgb/train/2017-02-03-11-44-56_los_altos_mountain_view_traffic_lights_bag/207374.png

**Comment by karstenBehrendt** [comment]
How about the additional_train.yaml?

Can you give the specific entry where it fails?
E.g. in line 126 insert
```
import pdb
pdb.set_trace()
and then check train_labels[0]

```
(or in super easy)
```
print(type(train_labels))
print(train_labels[0])
```
I just downloaded and re-ran the complete pipeline, and unfortunately could not reproduce the issue

**Comment by GenuineYZR** [comment]
@karstenBehrendt 
I inserted these bold lines before line 127 for testing

`# one entry for each image in a folder/video to check their sizes later`
**`print(type(train_labels))# for testing`
`print(train_labels[0]) # fortesting`
`print(train_labels[0]['path'].split('/')[-2]) # for testing`**
`train_videos = [train_label['path'].split('/')[-2] for train_label in train_labels]`

and the first two lines worked fine, they got me the results like this:

> <class 'list'>
{'boxes': [], 'path': 'D:\\Udacity\\Self-driving_car\\projects\\Term3\\P3\\rgb\\dataset_train_rgb\\rgb\\train\\2017-02-03-11-44-56_los_altos_mountain_view_traffic_lights_bag\\207374.png'}

but the third line seems did the damage:

> File "D:\Udacity\Self-driving_car\projects\Term3\P3\models\research\bstld\tf_object_detection\to_tfrecords.py", line 129, in split_train_labels
    print(train_labels[0]['path'].split('/')[-2]) # for testing
IndexError: list index out of range

I have been thinking of this, the **train_label[path]** seems to have '\\' instead of '/' which may cause problems when calling the **split('/')** function? 
The **train_labels** list results from the **get_all_labels()** function, is there any possibility it is related?

**Comment by karstenBehrendt** [comment]
You are on a windows system. Paths are handled with backslashes there. I don't understand why the first two seem to work.

You should be able to fix this issue by replacing the slash by a backslash, i.e.
` train_videos = [train_label['path'].split('\')[-2] for train_label in train_labels]`

For more debugging I'd recommend (untested)
```
train_videos = []
for train_label in train_labels:
    try:
        train_videos.append(train_label['path'].split('\')[-2])
    except IndexError:
        print("This one throws: {}".format(train_label))
```

One os independent (untested) option would likely be
` train_videos = [os.path.split(os.path.split(train_label['path'][0])[1] for train_label in train_labels]`

I will only be able to test this tomorrow. I did not test any of the code on windows, so there may be further issues but I can't think of any obvious right now. I will update the repo tomorrow- let me know if one of the solutions works

**Comment by GenuineYZR** [comment]
@karstenBehrendt 
I haven't expected it to be an os related issue, thanks for the patience!
The first solution did the job nicely! One point I found is that in windows **'\\'** seems to be used for the os default directory path while the **'\\\\'** is for the string in programming language. So I ended up replacing the **'/'** with **'\\\\'**.
BTW, just a little curious, was Linux the os you tested your code on?

**Comment by karstenBehrendt** [comment]
I changed the split approach to us os.path.split which should be OS independent.

`train_videos = [os.path.split(os.path.split(train_label['path'][0])[1] for train_label in train_labels]`

I hope this will work on Windows, also. Please let me know if it doesn't.
